name: BedWars
api: [4.0.0, 3.0.0]
version: 1.0.0
author: VixikCZ, piyushbest
main: eggwars\EggWars
description: BedWars minigame plugin
load: POSTWORLD

permissions:
  bw.cmd:
    description: Permission for ALL EggWars Commands
    default: op
    children:
      bw.cmd.vote:
        default: true
        description: Permission for /vote
      bw.cmd.team:
        default: true
        description: Permission for /team
      bw.cmd.help:
        default: op
        description: Permission to /ew help
      bw.cmd.create:
        default: op
        description: Permission to /ew create
      bw.cmd.arenas:
        default: op
        description: Permission to /ew arenas
      bw.cmd.set:
        default: op
        description: Permission to /ew set
      bw.cmd.info:
        default: true
        description: Permission to /ew info
      bw.cmd.shop:
        default: true
        description: Permission to /ew shop
      bw.cmd.level:
        default: op
        description: Permissions for level commands
        children:
          bw.cmd.level.add:
            default: op
            description: Permission to /ew level add
          bw.cmd.level.set:
            default: op
            description: Permission to /ew level set
